
server:
  port: 8762

spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: tounima.0
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml # 配置mapper路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
